name: Building OrangeFox recovery

on:
#  release:
#    types: [published]
#  push:
#    branches:
#      - master
#    paths:
#      - '.config'
#  schedule:
#    - cron: 0 8 * * 5
# Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  watch:
    types: [started]

env:
  DEVICE: phoenix
  DT_LINK: https://github.com/hraj9258/ofox_phoenix -b test1
  DT_PATH: device/xiaomi/phoenix
  CHAT_ID: ${{ secrets.TEST_CHAT_ID }}
  BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
  TARGET: recoveryimage
  TZ: Asia/Kolkata

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
       - name: Checkout
         uses: actions/checkout@master
         
       - name: Initializing environment
         run: |
            sudo rm -rf /usr/share/dotnet /etc/mysql /etc/php /etc/apt/sources.list.d
            docker rmi `docker images -q`
            sudo apt-get remove account-plugin-facebook account-plugin-flickr account-plugin-jabber account-plugin-salut account-plugin-twitter account-plugin-windows-live account-plugin-yahoo aisleriot brltty duplicity empathy empathy-common example-content gnome-accessibility-themes gnome-contacts gnome-mahjongg gnome-mines gnome-orca gnome-screensaver gnome-sudoku gnome-video-effects gnomine landscape-common libreoffice-avmedia-backend-gstreamer libreoffice-base-core libreoffice-calc libreoffice-common libreoffice-core libreoffice-draw libreoffice-gnome libreoffice-gtk libreoffice-impress libreoffice-math libreoffice-ogltrans libreoffice-pdfimport libreoffice-style-galaxy libreoffice-style-human libreoffice-writer libsane libsane-common mcp-account-manager-uoa python3-uno rhythmbox rhythmbox-plugins rhythmbox-plugin-zeitgeist sane-utils shotwell shotwell-common telepathy-gabble telepathy-haze telepathy-idle telepathy-indicator telepathy-logger telepathy-mission-control-5 telepathy-salut totem totem-common totem-plugins printer-driver-brlaser printer-driver-foo2zjs printer-driver-foo2zjs-common printer-driver-m2300w printer-driver-ptouch printer-driver-splix
            git config --global user.name "Himanshu Raj"
            git config --global user.email "himanshurajkush@gmail.com"         
            sudo -E apt-get -y purge azure-cli ghc* zulu* hhvm llvm* firefox google* dotnet* powershell openjdk* mysql* php* 
            sudo -E apt-get clean 
            sudo -E apt-get -qq update
            sudo apt install git aria2 -y
            git clone https://gitlab.com/OrangeFox/misc/scripts &&cd scripts
            sudo bash setup/android_build_env.sh
            sudo bash setup/install_android_sdk.sh
            
       - name: Sync OrangeFox recovery source and device tree
         run: |
             mkdir ~/OrangeFox_10
             cd ~/OrangeFox_10
             git clone https://gitlab.com/hraj9258/sync.git
             cd ~/OrangeFox_10/sync
             echo 'y' | ./get_fox_10.sh ~/OrangeFox_10/fox_10.0
             cd ~/OrangeFox_10/fox_10.0
             git clone $DT_LINK $DT_PATH
             
       - name: Building OrangeFox Recovery
         run: |
              cd ~/OrangeFox_10/fox_10.0
              source build/envsetup.sh &&export ALLOW_MISSING_DEPENDENCIES=true &&export FOX_USE_TWRP_RECOVERY_IMAGE_BUILDER=1 &&export LC_ALL="C"
              lunch omni_phoenix-eng &&mka recoveryimage

       - name: Uploading recovery image
         run: |
              cd out/target/product/$DEVICE
              curl -F chat_id=$CHAT_ID -F document=@OrangeFox-Unofficial-phoenix.zip https://api.telegram.org/bot$BOT_TOKEN/sendDocument
              sudo zip -r9 ofox-phoenix.zip recovery.img
              curl -F chat_id=$CHAT_ID -F document=@ofox-phoenix.zip https://api.telegram.org/bot$BOT_TOKEN/sendDocument
              curl -sL https://git.io/file-transfer | sh
              ./transfer wet OrangeFox-Unofficial-phoenix.zip
              ./transfer wet OrangeFox-Unofficial-phoenix.img
              ./transfer wet *.zip